### ISSUE TITLE
Build error on Ubuntu 20.04 without GPU

### ISSUE THREAD

**Issue by MilkFather** [peridyno/peridyno#30]
I ran this code:
```shell
mkdir build
cd build
cmake -DPERIDYNO_GPU_BACKEND=NO_BACKEND ..
make
```
I ran into this error:
```shell
.../peridyno/src/Framework/NodePort.h:241:36: error: cannot define member function ‘dyno::NodePort::hasNode’ within ‘dyno::MultipleNodePort<T>’
```

I tried changing `NodePort::hasNode` into `hasNode` and it builds (with more errors, detailed in another issue).

**Comment by hanxingyixue** [comment]
Hello, we are updating the code for the Linux platform. Please download https://gitee.com/peridyno/peridyno The Linux repository code in. Thank you for your attention.
