### ISSUE TITLE
More build errorrs on Ubuntu 20.04 without GPU 

### ISSUE THREAD

**Issue by MilkFather** [peridyno/peridyno#31]
Follows #30.

I have no CUDA nor Vulkan installed, build fails with more errors.

<details>
<summary>Tons of garbage output</summary>
<pre>/home/heather/code/peridyno/src/Core/Primitive/Primitive3D.h:121:20: error: expected nested-name-specifier
  121 |   typedef typename Vector<Real, 2> Coord2D;
      |                    ^~~~~~~~~~~~~~~
/home/heather/code/peridyno/src/Core/Primitive/Primitive3D.h:121:36: error: invalid declarator before ‘Coord2D’
  121 |   typedef typename Vector<Real, 2> Coord2D;
      |                                    ^~~~~~~
/home/heather/code/peridyno/src/Core/Primitive/Primitive3D.h:122:20: error: expected nested-name-specifier
  122 |   typedef typename Vector<Real, 3> Coord3D;
      |                    ^~~~~~~~~~~~~~~
/home/heather/code/peridyno/src/Core/Primitive/Primitive3D.h:122:36: error: invalid declarator before ‘Coord3D’
  122 |   typedef typename Vector<Real, 3> Coord3D;
      |                                    ^~~~~~~
/home/heather/code/peridyno/src/Core/Primitive/Primitive3D.h:129:40: error: ‘Coord3D’ does not name a type
  129 |   DYN_FUNC TPoint3D& operator = (const Coord3D& p);
      |                                        ^~~~~~~
...<pre>
</details>

**Comment by hanxingyixue** [comment]
Hello, we are updating the code for the Linux platform. Please download https://gitee.com/peridyno/peridyno The Linux repository code in. Thank you for your attention.
