### ISSUE TITLE
Link error with CUDA 11.1 on Windows 10

### ISSUE THREAD

**Issue by ZaiqiangWu** [peridyno/peridyno#35]
Undefined reference to '_Z3powfi' in 'Topology.dir/Debug/SparseGridHash.obj'	Topology

**Comment by clouddon** [comment]
How about clear up all temporary files?

**Comment by ZaiqiangWu** [comment]
> How about clear up all temporary files?

Thanks for your advice, I tried it but still doesn't work. However, I found that upgrading CUDA from 11.1 to 12.1 solves my problem.
