### ISSUE TITLE
为节点的menu添加“更新下游节点”、“根据上游节点更新”功能

### ISSUE THREAD

**Issue by bigshark151** [peridyno/peridyno#55]
期望在节点右键菜单添加“更新下游节点”、“根据上游节点更新”功能。以让用户自定义何时在改变上游节点时实时更新下游节点。

**Comment by clouddon** [comment]
<img width="442" alt="22" src="https://github.com/peridyno/peridyno/assets/4082882/1f2d5c6f-8c62-4c96-97ec-67c570a0430c">
